-- AlterTable: add ON UPDATE CURRENT_TIMESTAMP so Prisma @updatedAt is DB-enforced
ALTER TABLE `Statistic` MODIFY `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3);
